name: "Rusalka - wxn0brP"
description: "wxn0brP's typescript ci"
author: "wxn0brP"

branding:
  color: "purple"
  icon: "hash"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install Bun
      shell: bash
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 22
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      shell: bash
      run: |
        bun install

    - name: Run TS script with Bun
      shell: bash
      id: rusalka
      run: bun $GITHUB_ACTION_PATH/src/index.ts

    - name: Publish package to npm
      if: steps.rusalka.outputs.npm_tag != ''
      shell: sh
      run: |
        npm install -g npm@latest
        npm publish --access public --tag $NPM_TAG
      env:
        NODE_AUTH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NPM_TAG: ${{ steps.rusalka.outputs.npm_tag }}

inputs:
  GITHUB_TOKEN:
    description: "GitHub token for publishing to npm"
    required: false

outputs:
  message:
    value: "Rusalka is majestic"
    description: "Majestic exit"
