name: "Rusalka - wxn0brP"
description: "wxn0brP's typescript ci"
author: "wxn0brP"

branding:
  color: "purple"
  icon: "hash"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install Bun
      shell: bash
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 22
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      shell: bash
      run: |
        bun install

    - name: Run TS script with Bun
      shell: bash
      run: bun $GITHUB_ACTION_PATH/src/index.ts

outputs:
  message:
    value: "Rusalka is majestic"
    description: "Majestic exit"
