name: "Rusalka - wxn0brP"
description: "wxn0brP's typescript ci"
author: "wxn0brP"

branding:
  color: "purple"
  icon: "hash"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org/

    - name: Setup Workflow
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        bun install

    - name: Install dependencies
      shell: bash
      run: |
        bun install

    - name: Run TS script with Bun
      shell: bash
      id: rusalka
      run: bun $GITHUB_ACTION_PATH/src/index.ts

    - name: Publish package to npm
      if: steps.rusalka.outputs.npm_tag != ''
      shell: sh
      run: |
        npm install -g npm@latest
        npm publish --access public --tag $NPM_TAG
      env:
        NODE_AUTH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NPM_TAG: ${{ steps.rusalka.outputs.npm_tag }}

    - name: Upload to gh pages
      if: steps.rusalka.outputs.typedocs != ''
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
        publish_dir: ./typedocs-generated
        destination_dir: ${{ steps.rusalka.outputs.destination_dir }}
        publish_branch: ${{ steps.rusalka.outputs.typedocs }}

inputs:
  GITHUB_TOKEN:
    description: "GitHub token for publishing to npm"
    required: false

outputs:
  message:
    value: "Rusalka is majestic"
    description: "Majestic exit"

  npm_tag:
    value: ${{ steps.rusalka.outputs.npm_tag }}
    description: "NPM tag"
